#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# USERS
getUsers:
  path:       /users
  controller: App\Controller\UserController::getUsers
  methods:    GET

getUser:
  path:       /user/{id}
  controller: App\Controller\UserController::getUser1
  methods:    GET
  defaults:
    id: 1

postUser:
  path:       /users
  controller: App\Controller\UserController::createUser
  methods:    POST

patchUser:
  path:       /user/{id}
  controller: App\Controller\UserController::patchUser
  methods:    PATCH
  defaults:
    id: 1

deleteUser:
  path:       /user/{id}
  controller: App\Controller\UserController::deleteUser
  methods:    DELETE
  defaults:
    id: 1

# GAMES
getGames:
  path:       /games
  controller: App\Controller\GameController::getGames
  methods:    GET

getGame:
  path:       /game/{id}
  controller: App\Controller\GameController::getGame
  methods:    GET
  defaults:
    id: 1

getUserGames:
  path:       /games/{userId}
  controller: App\Controller\GameController::getUserGames
  methods:    GET
  defaults:
    userId: 1

postGame:
  path:       /games
  controller: App\Controller\GameController::createGame
  methods:    POST

patchGame:
  path:       /game/{id}
  controller: App\Controller\GameController::patchGame
  methods:    PATCH
  defaults:
    id: 1

deleteGame:
  path:       /game/{id}
  controller: App\Controller\GameController::deleteGame
  methods:    DELETE
  defaults:
    id: 1

# EXPANSION PACKS
getExpansions:
  path:       /expansions
  controller: App\Controller\ExpansionController::getExpansions
  methods:    GET

getExpansion:
  path:       /expansion/{id}
  controller: App\Controller\ExpansionController::getExpansion
  methods:    GET
  defaults:
    id: 1

getGameExpansion:
  path:       /expansions/{gameId}
  controller: App\Controller\ExpansionController::getGameExpansions
  methods:    GET
  defaults:
    gameId: 1

postExpansion:
  path:       /expansions
  controller: App\Controller\ExpansionController::createExpansion
  methods:    POST

patchExpansion:
  path:       /expansion/{id}
  controller: App\Controller\ExpansionController::patchExpansion
  methods:    PATCH
  defaults:
    id: 1

deleteExpansion:
  path:       /expansion/{id}
  controller: App\Controller\ExpansionController::deleteExpansion
  methods:    DELETE
  defaults:
    id: 1
